os:
  - linux
  - osx
language: node_js
node_js:
  - "10.16.0"
services:
  - redis-server
install:
  - "yarn"
script:
  - "yarn build"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
env:
  - YARN_GPG=no
