name: CLA Assistant
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
jobs:
  claAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: Check signed CLA
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        with:
          path-to-signatures: cla-signatures.json
          path-to-document: https://github.com/koj-co/.github/blob/master/CLA.md
          allowlist: dependabot-preview[bot], dependabot[bot], greenkeeper[bot], *bot, bot*
          remote-organization-name: koj-co
          remote-repository-name: .github
          signed-commit-message: ":wrench: @$contributorName has signed the CLA in #$pullRequestNo"
          create-file-commit-message: ":wrench: Creating a file for storing CLA signatures"
          custom-allsigned-prcomment: "✍️ All contributors have signed the CLA"
          custom-notsigned-prcomment: "Thanks for your submission! We ask that $you sign our [Contributor License Agreement]($pathToCLADocument) before we can accept your contribution. You can sign the CLA by adding a comment below using this text:"
